version: '3'
services:
  resilio:
    image: lsioarmhf/resilio-sync
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.resilio==true
      labels:
        - traefik.enable=true
        - traefik.backend=resilio
        - traefik.frontend.passHostHeader=true
        - traefik.docker.network=traefik
        - traefik.port=8888
        - traefik.frontend.rule=Host:resilio.cluster
    volumes:
      - resilio/data:/sync
      - resilio/config:/config
    networks:
      - traefik

networks:
  traefik:
    external: true
